title: Polypeptide diffusion calculator (ppdiffuse)
description: "Web-based calculator for voltage-driven transport of polypeptides through nanopores"

baseurl: "/ppdiffuse"
rooturl: ""

theme: jekyll-theme-midnight
markdown: kramdown
permalink: pretty
encoding: UTF-8